sudo: required
services:
  - docker

before_install:
  - docker build -t csoulioti/react-fibonacci-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run csoulioti/react-fibonacci-docker npm run test -- --coverage

after_success:
  - docker build -t csoulioti/react-fibonacci-docker-client ./client
  - docker build -t csoulioti/react-fibonacci-docker-nginx ./nginx
  - docker build -t csoulioti/react-fibonacci-docker-server ./server
  - docker build -t csoulioti/react-fibonacci-docker-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push then to docker hub
  - docker push csoulioti/react-fibonacci-docker-client
  - docker push csoulioti/react-fibonacci-docker-nginx
  - docker push csoulioti/react-fibonacci-docker-server
  - docker push csoulioti/react-fibonacci-docker-worker
